[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/tools/recommended-tools"
  to = "/tools/recommended-tools"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
